try opa

diff --git a/templates/ilpt/commands.yaml b/templates/ilpt/commands.yaml
--- a/templates/ilpt/commands.yaml
+++ b/templates/ilpt/commands.yaml
@@ -3,16 +3,26 @@ commands:
     priority: 100
     before: true
     script: |
-      import TerraTag
-      new TerraTag().loadTool(
-        "$workingDirectory",
-        "$bashToolsDirectory",
-        "0.7.3")
-      "Terratag download completed"
+          import Opa
+
+          new Opa().loadTool(
+            "$workingDirectory",
+            "$bashToolsDirectory",
+            "0.44.0")
+          "Opa Download Completed..."
   - runtime: "BASH"
     priority: 200
-    before: true
-    script: |
-      cd $workingDirectory
-      pier
-      terratag -tags="{\"environment_id\": \"development\"}"
+    after: true
+        script: |
+          cd $workingDirectory;
+          terraform show -json terraformLibrary.tfPlan > tfplan.json;
+          echo "Checkint Open Policy Agent Policy";
+          opaCheck=$(opa exec --decision terraform/analysis/notallowedlocationsmsg --bundle .terrakube/toolsRepository/policy/ tfplan.json | jq '.result[0].result');
+
+          if [ "$opaCheck" == "true" ]; then
+            echo "Policy is valid"
+            exit 0
+          else
+            echo "Policy is invalid"
+            exit 1
+          fi
